[package]
name = "mirror"
version = "0.1.0"
authors = ["Zachary Vance <za3k@za3k.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
